config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :topics
  resources :articles
  resources :users

  get   '/home',    to: 'static_pages#home'
  get   '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  get   '/logout',  to: 'sessions#destroy'
  get   '/signup',  to: 'users#new'

  get   '/profile', to: 'users#show'
  get   '/profile/edit', to: 'users#edit', as: :edit_profile
  patch '/profile/edit', to: 'users#update', as: :update_profile
  get   '/users/:id/delete', to: 'users#destroy', as: :delete_user

  # error pages
  get "/404", to: "errors#not_found", as: :not_found
  get "/500", to: "errors#internal_error", as: :internal_error

  post '/articles/new', to: 'articles#create'

  get   '/:topic_id', to: 'topics#show'

  get   '/:topic_id/new',                 to: 'articles#new', as: :new_topic_article
  get   '/:topic_id/:article_id',         to: 'articles#show', as: :show_article
  patch '/:topic_id/:article_id',         to: 'articles#update', as: :update_topic_article
  get   '/:topic_id/:article_id/edit',    to: 'articles#edit', as: :edit_topic_article
  get   '/:topic_id/:article_id/delete',  to: 'articles#destroy', as: :delete_topic_article

  #get '*unmatched_route', to: 'errors#not_found'
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :username, use: :slugged
  has_rich_text :article_content
  has_many_attached :images, dependent: :destroy

  VALID_SLUG_REGEX = /\A[a-z0-9]+(?:-[a-z0-9]+)*\z/i
  belongs_to :user
  belongs_to :topic
  validates :title,   presence: true, uniqueness: true
  validates :user_id, presence: true
  validates :topic_id, presence: true
  validates :article_content, presence: true, length: { minimum: 10, message: "Článek je příliš krátký" }
  validates :slug,    presence: true, length: { maximum: 50 }, format: { with: VALID_SLUG_REGEX }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user, only: [:create]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @article = Article.new
  end

  def show
    @article = Article.find_by(slug: params[:article_id])
    @user = @article.user
  end

  def create
    @article = current_user.articles.build(article_params)
    @article.images.attach(params[:article][:images])
    if @article.save
      flash[:success] = "Příspěvek vytvořen"
      redirect_to profile_path
    else
      flash[:danger] = "Chyba"
      redirect_to root_url
    end
  end

  def update
    @article = Article.find_by(slug: params[:article_id])
    if @article.update(article_params)
      flash[:success] = "Článek úspěšně upraven"
      redirect_to show_article_path(@article.topic.slug, @article.slug)
    else
      flash[:danger] = "Chyba"
      render request.original_url
    end
  end

  def edit
    @article = Article.find_by(slug: params[:article_id])
  end

  def destroy
    @article.destroy
    flash[:success] = "Článek smazán"
    redirect_to root_url
  end

  private

    def set_topic
      @topic = Topic.find_by(slug: params[:topic_id])
      @articles = @topic.articles
    end

    def article_params
      params.require(:article).permit(:title, :article_content, :slug, :topic_id, images: [])
    end

    def correct_user
      @article = current_user.articles.find_by(slug: params[:article_id])
      flash[:danger] = "Článek není váš" if @article.nil?
      redirect_to root_url if @article.nil?
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<tr class="text-white">
    <td class="col-md-6 article-card">
      <%= link_to show_article_path(article.topic.slug, article.slug), class: "text-white article" do %>
        <h4 class="text-white"><%= article.title %></h4>
        <p class="text-white"><%= shorten(article).truncate(length, separator: ' ') %></p>
      <% end %>
    </td>
    <td><%= "#{created_at_time(article)}" %></td>
    <td><%= link_to article.user.full_name, article.user, class: "text-white" %></td>
</tr>

app/views/articles/_form.html.erb
<%= render 'shared/error_messages', object: f.object %>
<div class="field">

  <%= f.label :title, "Název" %>
  <%= f.text_field :title, class: "form-control mb-3", id: "title" %>

  <%= f.label :slug, "Slug" %>
  <%= f.text_field :slug, class: "form-control mb-3", id: "slug" %>

  <%= f.label :topic_id, "Kategorie" %>
  <%= f.select :topic_id, Topic.all.collect { |x| [x.title, x.id] }, {}, class: "form-select mb-3" %>

  <script>

      document.getElementById("title").onchange = function () {
          textToSlug()
      }

      function textToSlug() {
          var x = document.getElementById("slug");
          var y = document.getElementById("title")
          x.value = y.value.toString()                     // Cast to string
              .toLowerCase()                  // Convert the string to lowercase letters
              .normalize('NFD')       // The normalize() method returns the Unicode Normalization Form of a given string.
              .trim()                         // Remove whitespace from both sides of a string
              .replace(/\s+/g, '-')           // Replace spaces with -
              .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
              .replace(/\-\-+/g, '-');        // Replace multiple - with single -
          //copied from https://gist.github.com/thierryc
      }

  </script>

  <%= f.label :article_content, "Text" %>
  <%= f.rich_text_area :article_content, class: "text-dark bg-white mb-3 h-25" %>

  <%= f.submit "Nahrát", class: "btn btn-primary" %>
</div>

app/views/articles/edit.html.erb
<% content_for :title, "Upravit článek" %>
<h2>Upravit článek</h2>
<%= form_for(@article, url: update_topic_article_path, method: :patch, local: true) do |f|%>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">

    <%= f.label :title, "Název" %>
    <%= f.text_field :title, class: "form-control mb-3", id: "title" %>

    <%= f.label :slug, "Slug" %>
    <%= f.text_field :slug, class: "form-control mb-3", id: "slug" %>

    <%= f.label :topic_id, "Kategorie" %>
    <%= f.select :topic_id, Topic.all.collect { |x| [x.title, x.id] }, {}, class: "form-select mb-3" %>

    <script>

        document.getElementById("title").onchange = function () {
            textToSlug()
        }

        function textToSlug() {
            var x = document.getElementById("slug");
            var y = document.getElementById("title")
            x.value = y.value.toString()                     // Cast to string
                .toLowerCase()                  // Convert the string to lowercase letters
                .normalize('NFD')       // The normalize() method returns the Unicode Normalization Form of a given string.
                .trim()                         // Remove whitespace from both sides of a string
                .replace(/\s+/g, '-')           // Replace spaces with -
                .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
                .replace(/\-\-+/g, '-');        // Replace multiple - with single -
            //copied from https://gist.github.com/thierryc
        }

    </script>

    <%= f.label :article_content, "Text" %>
    <%= f.rich_text_area :article_content, class: "text-dark bg-white mb-3 h-25" %>

    <%= f.submit "Nahrát", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/new.html.erb
<% content_for :title, "Nový článek" %>
<h2>Nový článek</h2>
<%= form_with(model: @article) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">

    <%= f.label :title, "Název" %>
    <%= f.text_field :title, class: "form-control mb-3", id: "title" %>

    <%= f.label :slug, "Slug" %>
    <%= f.text_field :slug, class: "form-control mb-3", id: "slug" %>

    <%= f.label :topic_id, "Kategorie" %>
    <%= f.select :topic_id, Topic.all.collect { |x| [x.title, x.id] }, {}, class: "form-select mb-3" %>

    <script>

        document.getElementById("title").onchange = function () {
            textToSlug()
        }

        function textToSlug() {
            var x = document.getElementById("slug");
            var y = document.getElementById("title")
            x.value = y.value.toString()                     // Cast to string
                .toLowerCase()                  // Convert the string to lowercase letters
                .normalize('NFD')       // The normalize() method returns the Unicode Normalization Form of a given string.
                .trim()                         // Remove whitespace from both sides of a string
                .replace(/\s+/g, '-')           // Replace spaces with -
                .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
                .replace(/\-\-+/g, '-');        // Replace multiple - with single -
            //copied from https://gist.github.com/thierryc
        }

    </script>

    <%= f.label :article_content, "Text" %>
    <%= f.rich_text_area :article_content, class: "text-dark bg-white mb-3 h-25" %>

    <%= f.submit "Nahrát", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/show.html.erb
<div class="container row">
  <div class="col-md-10">
    <h2><%= @article.title %></h2>
    <div>
      <%= link_to "Upravit článek", edit_topic_article_path, class: "btn btn-primary" %>
    </div>
  </div>
  <div class="col-md-2">
    <table>
      <tr>
        <th><%= link_to "#{@user.full_name}", @user, class: "text-white", style: "float: right" %></th>
      </tr>
      <tr>
        <th><%= created_at_time(@article) %></th>
      </tr>
    </table>
  </div>
  <div class="justify-content-center mt-3">
    <%= @article.article_content %>
  </div>
</div>