config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :topics
  resources :articles
  resources :users

  get   '/home',    to: 'static_pages#home'
  get   '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  get   '/logout',  to: 'sessions#destroy'
  get   '/signup',  to: 'users#new'

  get   '/profile', to: 'users#show'
  get   '/profile/edit', to: 'users#edit', as: :edit_profile
  patch '/profile/edit', to: 'users#update', as: :update_profile
  get   '/users/:id/delete', to: 'users#destroy', as: :delete_user

  # error pages
  get "/404", to: "errors#not_found", as: :not_found
  get "/500", to: "errors#internal_error", as: :internal_error

  post '/articles/new', to: 'articles#create'

  get   '/:topic_id', to: 'topics#show'

  get   '/:topic_id/new',                 to: 'articles#new', as: :new_topic_article
  get   '/:topic_id/:article_id',         to: 'articles#show', as: :show_article
  patch '/:topic_id/:article_id',         to: 'articles#update', as: :update_topic_article
  get   '/:topic_id/:article_id/edit',    to: 'articles#edit', as: :edit_topic_article
  get   '/:topic_id/:article_id/delete',  to: 'articles#destroy', as: :delete_topic_article

  #get '*unmatched_route', to: 'errors#not_found'
end

app/models/topic.rb
class Topic < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  VALID_SLUG_REGEX = /\A[a-z0-9]+(?:-[a-z0-9]+)*\z/i
  has_many :articles
  validates :title, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :slug, presence: true, length: { maximum: 50 }, format: { with: VALID_SLUG_REGEX }, uniqueness: true
  validates :description, presence: true, length: { maximum: 100 }

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic,     only: [:show, :edit]
  before_action :admin_user,    only: [:new, :edit, :update, :destroy, :create, :index]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find_by(slug: params[:topic_id])
    @articles = Article.includes(:user, :topic).with_all_rich_text.paginate(page: params[:page], per_page: 10).order(:title)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    respond_to do |format|
      if @topic.save
        format.html { redirect_to root_url, notice: "Kategorie #{@topic.title} úspěšně vytvořena" }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, notice: 'Něco se pokazilo' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @topic = Topic.find_by(slug: params[:id])
  end

  def update
    @topic = Topic.find_by(slug: params[:id])
    if @topic.update(topic_params)
      flash[:success] = "Rubrika úspěšně upravena"
      redirect_to topics_path
    else
      flash[:danger] = "Chyba"
      redirect_to request.original_url
    end
  end

  def destroy
    Topic.find(params[:id]).destroy
    flash[:success] = "Rubrika smazána"
    redirect_to root_url
  end

  private

    def set_topic
      @topic = Topic.find_by(slug: params[:id])
    end

    def topic_params
      params.require(:topic).permit(:title, :description, :slug, :topic_id)
    end

end

app/helpers/topics_helper.rb
module TopicsHelper

  def shorten(article)
    Loofah.fragment(article.article_content.to_plain_text).scrub!(:strip).text
  end

end

app/views/topics/_form.html.erb
<%= form_with(model: @topic) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= @topic.title %>
  <div class="field">

    <%= f.label :title, "Název" %>
    <%= f.text_field :title, class: "form-control mb-3", id: "title" %>

    <%= f.label :description, "Popis" %>
    <%= f.text_field :description, class: "form-control mb-3", id: "description" %>

    <%= f.label :slug, "Slug" %>
    <%= f.text_field :slug, class: "form-control mb-3", id: "slug" %>

    <script>

        document.getElementById("title").onchange = function (){ textToSlug() }
        function textToSlug(){
            var x = document.getElementById("slug");
            var y = document.getElementById("title")
            x.value =     y.value.toString()                     // Cast to string
                .toLowerCase()                  // Convert the string to lowercase letters
                .normalize('NFD')       // The normalize() method returns the Unicode Normalization Form of a given string.
                .trim()                         // Remove whitespace from both sides of a string
                .replace(/\s+/g, '-')           // Replace spaces with -
                .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
                .replace(/\-\-+/g, '-');        // Replace multiple - with single -
            //copied from https://gist.github.com/thierryc
        }

    </script>
    <%= f.submit "Nahrát", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<tr>
  <td><%= topic.title %></td>
  <td><%= topic.description %></td>
  <td><%= created_at_time(topic)%></td>
  <td>
    <%= link_to "Upravit #{topic.title}", edit_topic_path(topic), class: "text-white" %>
  </td>
</tr>

app/views/topics/edit.html.erb
<% content_for :title, "Upravit rubriku" %>
<h2>Upravit rubriku</h2>
<%= render 'form' %>

app/views/topics/index.html.erb
<% content_for :title, "Kategorie" %>
<%= link_to "Nová rubrika", new_topic_path, class: "btn btn-primary mb-3" if logged_in? %>
<table class="table table-bordered text-white mt-3">
  <thead>
  <tr>
    <th scope="col">Název</th>
    <th scope="col">Popis</th>
    <th scope="col">Vytvořeno</th>
    <th scope="col">Možnosti</th>
  </tr>
  </thead>
  <tbody>
  <%= render @topics %>
  </tbody>
</table>

app/views/topics/new.html.erb
<% content_for :title, "Nová rubrika" %>
<h2>Nová rubrika</h2>
<%= render 'form' %>

app/views/topics/show.html.erb
<%= link_to "Nový článek", new_topic_article_path, class: "btn btn-primary mb-3" if logged_in? %>
<% if @topic.articles.any? %>
  <table class="table text-white mt-3">
    <thead>
    <tr>
      <th scope="col">Název</th>
      <th scope="col">Vytvořeno</th>
      <th scope="col">Autor</th>
    </tr>
    </thead>
    <tbody>
    <%= will_paginate @articles, :previous_label => 'Předchozí', :next_label => 'Další' %>
    <%= render @articles, length: 200 %>
    </tbody>
  </table>
  </table>
<% else %>
  <div class="mt-3">Kategorie
    <strong><%= @topic.title %></strong>
    ještě nemá žádné příspěvky
  </div>
<% end %>