config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :topics
  resources :articles
  resources :users

  get   '/home',    to: 'static_pages#home'
  get   '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  get   '/logout',  to: 'sessions#destroy'
  get   '/signup',  to: 'users#new'

  get   '/profile', to: 'users#show'
  get   '/profile/edit', to: 'users#edit', as: :edit_profile
  patch '/profile/edit', to: 'users#update', as: :update_profile
  get   '/users/:id/delete', to: 'users#destroy', as: :delete_user

  # error pages
  get "/404", to: "errors#not_found", as: :not_found
  get "/500", to: "errors#internal_error", as: :internal_error

  post '/articles/new', to: 'articles#create'

  get   '/:topic_id', to: 'topics#show'

  get   '/:topic_id/new',                 to: 'articles#new', as: :new_topic_article
  get   '/:topic_id/:article_id',         to: 'articles#show', as: :show_article
  patch '/:topic_id/:article_id',         to: 'articles#update', as: :update_topic_article
  get   '/:topic_id/:article_id/edit',    to: 'articles#edit', as: :edit_topic_article
  get   '/:topic_id/:article_id/delete',  to: 'articles#destroy', as: :delete_topic_article

  #get '*unmatched_route', to: 'errors#not_found'
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username

  VALID_NAME_REGEX = /\A[\p{L} ,.'-]+$\z/i
  VALID_USER_REGEX = /\A[a-zA-Z0-9]+([_]?[a-zA-Z0-9]+)*\z/i
  validates :username, format: { with: VALID_USER_REGEX, message: "Uživatelské jméno obsahuje nepovolené znaky" }, uniqueness: true, presence: true
  validates :full_name, format: { with: VALID_NAME_REGEX, message: "Celé jméno obsahuje nepovolené znaky" }, presence: true, on: [:create, :update]
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Špatný formát emailové adresy" }
  validates :password_digest, presence: true, length: { minimum: 6 }
  # has_many :articles, dependent: :nullify_then_purge # miss hannigan gem, use in production, tests dont pass if enabled
  has_many :articles, dependent: :delete_all
  before_save { self.email = email.downcase }
  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_logged_user, only: :show
  before_action :logged_in_user,  only: [:edit, :update, :destroy]
  before_action :correct_user,    only: [:edit, :update]
  before_action :admin_user,      only: [:index, :destroy]

  def index
    @users = User.where.not(id: current_user.id).all.paginate(page: params[:page], per_page: 10).order(:username)
  end

  def show
    if current_user.nil?
      @user = User.find_by(username: params[:id])
      @other_user = @user
    else
      @user = current_user
      if request.path == "/profile"
        @other_user = @user
      else
        @other_user = User.find_by(username: params[:id])
      end
    end
    @articles = Article.includes(:user, :topic).where(user_id: @other_user.id).with_all_rich_text.paginate(page: params[:page], per_page: 10).order(:title)
  end

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to login_url, notice: "Uživatel #{@user.username} úspěšně vytvořen" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, notice: 'Něco se pokazilo' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = current_user
    if @user.authenticate(user_params[:password])
      if @user.update(params.require(:user).permit(:full_name, :email, :password))
        flash[:success] = "Profil aktualizován"
        redirect_to profile_url
      else
        @user.errors.full_messages.each do |msg|
          flash[:danger] = msg
        end
        redirect_to profile_url
      end
    else
      flash[:danger] = "Špatné nebo chybějící heslo, pro změnu údajů zadejte stávající heslo"
      redirect_to profile_url
    end
  end

  def destroy
    User.find_by(username: params[:id]).destroy
    flash[:success] = "Uživatel smazán"
    redirect_to users_url
  end

  private

    def check_current_password
      user = User.find(params[:id])
      user.authenticate(params[:current_password]).present?
    end

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :full_name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = current_user
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/users_helper.rb
module UsersHelper

  DATE_FORMAT = "%d. %m. %Y %H:%M"

  def not_logged_user
    @other_user = User.find_by(username: params[:id])
    @user = @other_user
  end

  def admin_user
    unless is_admin?(current_user)
      flash[:danger] = "Nedostatečné oprávnění"
      redirect_to(root_url)
    end
  end

  def is_admin?(user)
    user.role == "ADMIN" unless user.nil?
  end

  def registered_at_time(user)
    user.created_at.strftime(DATE_FORMAT)
  end

  def last_login_time(user)
    user.last_login.present? ? user.last_login.strftime(DATE_FORMAT) : "nikdy"
  end

end

app/views/users/_user.html.erb
<tr class="text-white">
  <td><%= link_to "#{user.username}", user_path(user), class: "text-white" %></td>
  <td><%= user.full_name %></td>
  <td><%= user.email %></td>
  <td><%= user.role %></td>
  <td><%= last_login_time(user) %></td>
  <td><%= registered_at_time(user) %></td>
  <td><%= link_to "Smazat", delete_user_path(user), method: :post, data: { confirm: 'Potvrdit' }, class: "text-white" %></td>
</tr>

app/views/users/edit.html.erb
<% content_for(:title, "Změna údajů") %>
<h1>Změnit údaje</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_profile_path, method: :patch, local: true) do |f| %>

      <%= f.label :full_name, "Jméno a příjmení" %>
      <%= f.text_field :full_name, class: 'form-control' %>

      <%= f.label :email, "E-mail" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Pro potvrzení změn zadejte heslo" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Uložit změny", class: "btn btn-primary mt-3" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% content_for :title, "Uživatelé" %>
<%= link_to "Nový článek", new_topic_path, class: "btn btn-primary mb-3"%>
<table class="table table-bordered text-white mt-3">
  <thead>
  <tr>
    <th scope="col">Uživatelské jméno</th>
    <th scope="col">Celé jméno</th>
    <th scope="col">Email</th>
    <th scope="col">Práva</th>
    <th scope="col">Poslední přihlášení</th>
    <th scope="col">Datum registrace</th>
    <th scope="col">Možnosti</th>
  </tr>
  </thead>
  <tbody>
  <%= will_paginate @users, :previous_label => 'Předchozí', :next_label => 'Další' %>
  <%= render @users %>
  </tbody>
</table>

app/views/users/new.html.erb
<% content_for :title, "Registrace" %>
<h1>Registrace</h1>

<div class="row">
  <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :username, "Uživatelské jméno" %>
    <%= f.text_field :username, class: 'form-control' %>

    <%= f.label :full_name, "Jméno a příjmení" %>
    <%= f.text_field :full_name, class: 'form-control' %>

    <%= f.label :email, "E-mail" %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password, "Heslo" %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Potvrdit heslo" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Zaregistrovat", class: "btn btn-primary mt-3" %>
  <% end %>
</div>

app/views/users/show.html.erb
<% content_for(:title, "Profil") %>
<div class="row" style="height: max-content">
  <div class="row">
    <div><h1>Uživatel <%= "#{@other_user.full_name} (#{@other_user.username})"  %></h1></div>
    <% if (@user == @other_user || is_admin?(@user)) && current_user.present? %>
      <div class="col-md-4 mt-3">
        <table class="date-table">
          <tr>
            <td>Účet založen</td>
            <td><%= registered_at_time(@other_user) %></td>
          </tr>
          <tr>
            <td>Poslední přihlášení</td>
            <td><%= last_login_time(@other_user) %></td>
          </tr>
          <tr>
            <td>Uživatelské jméno</td>
            <td><%= @other_user.username %></td>
          </tr>
          <tr>
            <td>Celé jméno</td>
            <td><%= @other_user.full_name %></td>
          </tr>
        </table>
      </div>
    <% end %>
  </div>
  <div class="col-md-8 mt-3">
    Příspěvky uživatele <%= "#{@other_user.username}" %>
    <%= link_to "Nový příspěvek", new_article_path, method: :get, class: "btn btn-primary" if @other_user == @user && current_user.present? %>
    <% if @other_user.articles.any? %>
      <table class="table table-bordered text-white mt-3">
        <thead>
        <tr>
          <th scope="col">Název</th>
          <th scope="col">Vytvořeno</th>
          <th scope="col">Autor</th>
        </tr>
        </thead>
        <tbody>
        <%= will_paginate @articles, :previous_label => 'Předchozí', :next_label => 'Další' %>
        <%= render @articles, length: 50 %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>