config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :topics
  resources :articles
  resources :users

  get   '/home',    to: 'static_pages#home'
  get   '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  get   '/logout',  to: 'sessions#destroy'
  get   '/signup',  to: 'users#new'

  get   '/profile', to: 'users#show'
  get   '/profile/edit', to: 'users#edit', as: :edit_profile
  patch '/profile/edit', to: 'users#update', as: :update_profile
  get   '/users/:id/delete', to: 'users#destroy', as: :delete_user

  # error pages
  get "/404", to: "errors#not_found", as: :not_found
  get "/500", to: "errors#internal_error", as: :internal_error

  post '/articles/new', to: 'articles#create'

  get   '/:topic_id', to: 'topics#show'

  get   '/:topic_id/new',                 to: 'articles#new', as: :new_topic_article
  get   '/:topic_id/:article_id',         to: 'articles#show', as: :show_article
  patch '/:topic_id/:article_id',         to: 'articles#update', as: :update_topic_article
  get   '/:topic_id/:article_id/edit',    to: 'articles#edit', as: :edit_topic_article
  get   '/:topic_id/:article_id/delete',  to: 'articles#destroy', as: :delete_topic_article

  #get '*unmatched_route', to: 'errors#not_found'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-dark mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><h2 class="text-white">Aplikace</h2></a>
    <button class="navbar-toggler col-md-2 bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      Menu
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item"><%= link_to "Domů", root_path, class: "nav-link" %></li>
        <% if Topic.any? %>
          <% Topic.all.each do |topic| %>
            <li class="nav-item"><%= link_to "#{topic.title}", "/#{topic.slug}", class: "nav-link" %></li>
          <% end %>
        <% end %>
      </ul>
      <% if logged_in? %>
        <ul class="nav navbar-nav ms-auto">
          <li><%= link_to "Uživatelé", users_path, {:class => "nav-link"} if is_admin?(current_user) %></li>
          <li><%= link_to "Kategorie", topics_path, {:class => "nav-link"} if is_admin?(current_user) %></li>
        </ul>
        <div>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav">
              <li class="nav-item"><%= link_to "Profil", profile_path, {:class => "nav-link"} %></li>
              <li class="nav-item"><%= link_to "Nastavení", edit_profile_path, {:class => "nav-link"} %></li>
              <li class="dropdown-divider"></li>
              <li class="nav-item"><%= link_to "Odhlásit", logout_path, method: :get, :class => "nav-link" %></li>
            </ul>
          </div>
        </div>
      <% else %>
        <ul class="nav navbar-nav ms-auto">
          <li class="nav-item"><%= link_to "Přihlásit se", login_path, {:class => "nav-link"} %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <meta name="author" content="Ondřej Svoboda">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-secondary text-white">
    <%= render 'layouts/nav' %>
    <div class="container text-white">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
    <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>